"""
Django settings for online_shop project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from dotenv import load_dotenv

PROJECT_DIR = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BASE_DIR = Path(os.path.dirname(PROJECT_DIR))


load_dotenv(BASE_DIR / ".env")


def get_env_variable(name, default=None):
    try:
        return os.environ[name]
    except KeyError:
        if default is not None:
            return default
        raise ImproperlyConfigured(f"Missing required environment variable {name}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    "shop",  # custom app
    "tailwind",  # for Tailwind CSS
    "theme",  # Tailwind theme app
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by allauth
    # django-allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    # Optional social providers (uncomment as needed)
    # "allauth.socialaccount.providers.google",
    # "allauth.socialaccount.providers.facebook",
    # django-browser_reload
    # Two-Factor Authentication
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
]

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",  # Compress responses (must be first)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",  # Two-Factor Authentication
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Required by allauth
    "shop.middleware.analytics.VisitorTrackingMiddleware",  # Track visitor analytics
    "shop.middleware.ConnectionLogMiddleware",  # Track connections for security dashboard
    # "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "online_shop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            # os.path.join(PROJECT_DIR, "templates"),
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "shop.context_processors.cart_context",  # Cart info in all templates
            ],
        },
    },
]

WSGI_APPLICATION = "online_shop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(PROJECT_DIR, "static"),
    os.path.join(BASE_DIR, "theme", "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default storage settings, with the staticfiles storage updated.
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # ManifestStaticFilesStorage is recommended in production, to prevent
    # outdated JavaScript / CSS assets being served from cache
    # (e.g. after a Wagtail upgrade).
    # See https://docs.djangoproject.com/en/5.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000
# Increase max request body size for base64-encoded images (default is 2.5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB


# TAILWIND
TAILWIND_APP_NAME = "theme"

# STRIPE
STRIPE_SECRET_KEY = get_env_variable("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = get_env_variable("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET = get_env_variable("STRIPE_WEBHOOK_SECRET", None)

# EMAIL - Using Resend SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.resend.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "resend"
EMAIL_HOST_PASSWORD = get_env_variable("RESEND_API_KEY", "")
DEFAULT_FROM_EMAIL = "Blueprint Apparel <no-reply@blueprnt.store>"

# TWILIO SMS
TWILIO_ACCOUNT_SID = get_env_variable("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = get_env_variable("TWILIO_AUTH_TOKEN", "")
TWILIO_PHONE_NUMBER = get_env_variable("TWILIO_PHONE_NUMBER", "")

# DJANGO-ALLAUTH CONFIGURATION
SITE_ID = 1  # Required by django.contrib.sites

AUTHENTICATION_BACKENDS = [
    # Django default (needed for admin)
    "django.contrib.auth.backends.ModelBackend",
    # Allauth specific authentication methods
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth settings
ACCOUNT_LOGIN_METHODS = {"email", "username"}  # Allow login with username or email
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]  # Required signup fields
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "none"  # Skip email verification (change to "mandatory" for production)
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True

# Custom adapter for redirects
ACCOUNT_ADAPTER = "shop.adapters.CustomAccountAdapter"

# Redirect URLs
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_REDIRECT_URL = "/"

# Session settings
ACCOUNT_SESSION_REMEMBER = True  # Remember me by default

# Allauth settings (updated for django-allauth 0.60+)
ACCOUNT_LOGIN_METHODS = {"email"}  # Login via email only
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]  # Email required, no username

# Allauth rate limiting (bot protection)
# Limits login/signup attempts to prevent brute force and credential stuffing attacks
ACCOUNT_RATE_LIMITS = {
    # Limit login attempts: 5 per minute, 20 per hour per IP
    "login_failed": "5/m,20/h",
    # Limit signup attempts: 5 per minute per IP
    "signup": "5/m",
    # Limit password reset requests: 5 per minute per IP
    "reset_password": "5/m",
    # Limit email confirmation resend: 3 per hour per IP
    "confirm_email": "3/h",
}

# GEOIP SETTINGS
# Path to GeoLite2 database for visitor location tracking
GEOIP_PATH = os.path.join(BASE_DIR, "geoip")

# SECURITY HEADERS
# Prevent clickjacking attacks by preventing your site from being embedded in iframes
X_FRAME_OPTIONS = "DENY"

# Enable the browser's XSS filtering
SECURE_BROWSER_XSS_FILTER = True

# Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Make CSRF cookie httponly (not accessible via JavaScript)
CSRF_COOKIE_HTTPONLY = True

# Session cookie security
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF protection
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds

# CSRF cookie security
CSRF_COOKIE_SAMESITE = "Lax"

# Referrer policy - control how much information is sent in the Referer header
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# CACHING CONFIGURATION
# Use Redis for caching if REDIS_URL is set, otherwise use local memory cache
REDIS_URL = os.environ.get("REDIS_URL", "").strip()

if REDIS_URL:
    # Production: Use Redis for caching
    from .cache import get_cache_config

    CACHES = get_cache_config()
    # Use Redis for session storage as well
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "sessions"
else:
    # Development: Use local memory cache (no Redis needed)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# LOGGING CONFIGURATION
# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {module} {process:d} {thread:d} - {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {asctime} - {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django.log"),
            "maxBytes": 1024 * 1024 * 15,  # 15MB
            "backupCount": 10,
            "formatter": "verbose",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "django_errors.log"),
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["file", "error_file"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["file", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "shop": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "home": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}
