# Generated by Django 4.2.25 on 2025-11-20 05:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("line1", models.CharField(max_length=200)),
                ("line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=2)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "target_group",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'All Subscribers', 'New Customers', 'VIP'",
                        max_length=100,
                    ),
                ),
                (
                    "active_from",
                    models.DateTimeField(
                        blank=True, help_text="Campaign becomes active from this date", null=True
                    ),
                ),
                (
                    "active_until",
                    models.DateTimeField(
                        blank=True, help_text="Campaign remains active until this date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "uses_size",
                    models.BooleanField(
                        default=False, help_text="Does this category use size variants?"
                    ),
                ),
                (
                    "uses_color",
                    models.BooleanField(
                        default=False, help_text="Does this category use color variants?"
                    ),
                ),
                (
                    "uses_material",
                    models.BooleanField(
                        default=False, help_text="Does this category use material variants?"
                    ),
                ),
                (
                    "custom_attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom variant attributes specific to this category",
                    ),
                ),
                (
                    "common_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Common custom fields that products in this category typically have",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "send_to_all_active",
                    models.BooleanField(default=True, help_text="Send to all active subscribers"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Campaign",
                "verbose_name_plural": "Email Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("AWAITING_PAYMENT", "Awaiting payment"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                            ("SHIPPED", "Shipped"),
                            ("FULFILLED", "Fulfilled"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("shipping", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("stripe_checkout_id", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=255)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("label_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="shop.address",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="shop.address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Product name (e.g., "Classic T-Shirt")', max_length=255
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Product description and details"),
                ),
                (
                    "category_legacy",
                    models.CharField(
                        blank=True,
                        db_column="category",
                        db_index=True,
                        help_text="DEPRECATED: Old category field",
                        max_length=100,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Starting/base price for this product",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "featured",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Feature this product on homepage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_obj",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product category - determines available variant attributes",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                ("supplier", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in-transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("delayed", "Delayed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "date_shipped",
                    models.DateField(
                        blank=True, help_text="Date shipment left supplier", null=True
                    ),
                ),
                ("expected_date", models.DateField(help_text="Expected delivery date")),
                (
                    "date_received",
                    models.DateField(blank=True, help_text="Actual date received", null=True),
                ),
                (
                    "manufacturing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total manufacturing/production cost",
                        max_digits=10,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Shipping and freight cost",
                        max_digits=10,
                    ),
                ),
                (
                    "customs_duty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Customs duty and import fees",
                        max_digits=10,
                    ),
                ),
                (
                    "other_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Other fees (insurance, handling, etc.)",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-expected_date"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Main hero image for the homepage",
                        null=True,
                        upload_to="site/hero/",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Welcome to Blueprint",
                        help_text="Main headline on homepage",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True, help_text="Subheadline or description on homepage"
                    ),
                ),
                ("site_name", models.CharField(default="Blueprint Apparel", max_length=100)),
                ("site_description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("discord_url", models.URLField(blank=True)),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to show maintenance page to non-staff users",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="SMSCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "send_to_all_active",
                    models.BooleanField(default=True, help_text="Send to all active subscribers"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Campaign",
                "verbose_name_plural": "SMS Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("landing_page", models.CharField(max_length=500)),
                ("referrer", models.URLField(blank=True, max_length=1000, null=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("page_views", models.IntegerField(default=1)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("country_name", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("stripe_customer_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("marketing_emails", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Message"),
                            ("confirmation", "Confirmation Code"),
                            ("promotion", "Promotional Message"),
                            ("reminder", "Reminder"),
                            ("announcement", "Announcement"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "message_body",
                    models.TextField(
                        help_text="Use {variable_name} for dynamic content. Example: 'Hi {first_name}, your code is {code}'",
                        max_length=1600,
                    ),
                ),
                (
                    "auto_trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("on_subscribe", "On New Subscription"),
                            ("on_confirmation", "On Confirmation Request"),
                            ("scheduled", "Scheduled Campaign"),
                        ],
                        default="manual",
                        help_text="When should this template be automatically sent?",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("times_used", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Template",
                "verbose_name_plural": "SMS Templates",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SMSSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="site_form", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SMS Subscription",
                "verbose_name_plural": "SMS Subscriptions",
                "ordering": ["-subscribed_at"],
                "indexes": [
                    models.Index(fields=["is_active", "is_confirmed"], name="sms_campaign_idx"),
                    models.Index(fields=["-subscribed_at"], name="sms_subscribed_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone_number", models.CharField(max_length=17)),
                ("message_body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("undelivered", "Undelivered"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("twilio_sid", models.CharField(blank=True, max_length=34)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="shop.smscampaign",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="shop.smssubscription",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="shop.smstemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Log",
                "verbose_name_plural": "SMS Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="smscampaign",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="shop.smstemplate",
            ),
        ),
        migrations.CreateModel(
            name="SavedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="E.g., 'Home', 'Work', 'Mom's House'", max_length=50
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("line1", models.CharField(max_length=200, verbose_name="Address Line 1")),
                (
                    "line2",
                    models.CharField(blank=True, max_length=200, verbose_name="Address Line 2"),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="State/Province"),
                ),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "country",
                    models.CharField(default="US", help_text="2-letter country code", max_length=2),
                ),
                ("is_default_shipping", models.BooleanField(default=False)),
                ("is_default_billing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Saved addresses",
                "ordering": ["-is_default_shipping", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit - auto-generated if blank",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "variant_attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic variant attributes based on category configuration",
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price for this specific variant", max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "images",
                    models.JSONField(blank=True, default=list, help_text="List of image URLs"),
                ),
                (
                    "custom_fields",
                    models.JSONField(blank=True, default=dict, help_text="Custom key-value data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.color",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.material",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.size",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, max_length=1000, null=True)),
                ("referrer_domain", models.CharField(blank=True, max_length=255)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("country_name", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "viewed_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(fields=["-viewed_at"], name="shop_pagevi_viewed__7233af_idx"),
                    models.Index(fields=["path", "-viewed_at"], name="shop_pagevi_path_a54b91_idx"),
                    models.Index(
                        fields=["referrer_domain", "-viewed_at"],
                        name="shop_pagevi_referre_a7bbb8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(max_length=50)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Message"),
                            ("confirmation", "Confirmation Email"),
                            ("promotion", "Promotional Email"),
                            ("newsletter", "Newsletter"),
                            ("announcement", "Announcement"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject line. Supports variables like {first_name}",
                        max_length=200,
                    ),
                ),
                (
                    "html_body",
                    models.TextField(
                        help_text="HTML email body. Use {variable_name} for dynamic content."
                    ),
                ),
                (
                    "text_body",
                    models.TextField(
                        blank=True,
                        help_text="Plain text version (optional, will be auto-generated from HTML if empty)",
                    ),
                ),
                (
                    "auto_trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("on_subscribe", "On New Subscription"),
                            ("on_confirmation", "On Confirmation Request"),
                            ("scheduled", "Scheduled Campaign"),
                        ],
                        default="manual",
                        help_text="When should this template be automatically sent?",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("times_used", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="site_form", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email Subscription",
                "verbose_name_plural": "Email Subscriptions",
                "ordering": ["-subscribed_at"],
                "indexes": [
                    models.Index(fields=["is_active", "is_confirmed"], name="email_campaign_idx"),
                    models.Index(fields=["-subscribed_at"], name="email_subscribed_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("html_body", models.TextField()),
                ("text_body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="shop.emailcampaign",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="shop.emailsubscription",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="shop.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="shop.emailtemplate",
            ),
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Internal name for this discount", max_length=200),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Discount code (leave blank for auto-apply)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Off"),
                            ("fixed", "Fixed Amount Off"),
                            ("bogo", "Buy One Get One"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g., 20 for 20%) or fixed amount (e.g., 10.00 for $10 off)",
                        max_digits=10,
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum purchase amount to qualify",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times this discount can be used (blank = unlimited)",
                        null=True,
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                (
                    "valid_from",
                    models.DateTimeField(help_text="Discount becomes active at this time"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Discount expires at this time (blank = no expiration)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "applies_to_all",
                    models.BooleanField(
                        default=True, help_text="Apply to all products or specific products only"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific products this discount applies to (if not applying to all)",
                        related_name="discounts",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.cart",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shop.productvariant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Welcome Email', 'Day 3 Follow-up SMS'", max_length=200
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("snapchat", "Snapchat"),
                            ("youtube", "YouTube"),
                            ("promotion", "Promotion"),
                            ("product", "Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("custom_subject", models.CharField(blank=True, max_length=200)),
                ("custom_content", models.TextField(blank=True)),
                (
                    "send_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-send"),
                            ("draft", "Save as Draft"),
                            ("manual", "Manual Approval Required"),
                        ],
                        default="auto",
                        help_text="How this message should be sent",
                        max_length=20,
                    ),
                ),
                (
                    "media_urls",
                    models.TextField(
                        blank=True,
                        help_text="URLs for images, videos, or other media (one per line)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes, content ideas, or reminders"
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Send Immediately"),
                            ("delay", "Send After Delay"),
                            ("specific_date", "Send on Specific Date"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                (
                    "delay_days",
                    models.IntegerField(
                        default=0,
                        help_text="Days to wait before sending (if trigger_type is 'delay')",
                    ),
                ),
                (
                    "delay_hours",
                    models.IntegerField(default=0, help_text="Hours to wait before sending"),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Specific date/time to send (if trigger_type is 'specific_date')",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of this message in the campaign sequence"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="shop.campaign",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional discount to associate with this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_messages",
                        to="shop.discount",
                    ),
                ),
                (
                    "email_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.emailtemplate",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific products this message applies to (optional)",
                        related_name="campaign_messages",
                        to="shop.product",
                    ),
                ),
                (
                    "sms_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.smstemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["campaign", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0, help_text="Quantity ordered")),
                (
                    "received_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Actual quantity received (may differ from ordered)"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per unit for this variant in this shipment",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.shipment",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_items",
                        to="shop.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["shipment", "variant"],
                "unique_together": {("shipment", "variant")},
            },
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["product", "size", "color"], name="variant_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["is_active", "stock_quantity"], name="variant_stock_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="variant_sku_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-created_at"], name="product_created_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "-created_at"], name="product_active_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["featured", "is_active"], name="product_featured_idx"),
        ),
        migrations.AddIndex(
            model_name="connectionlog",
            index=models.Index(fields=["-timestamp"], name="shop_connec_timesta_363e3a_idx"),
        ),
        migrations.AddIndex(
            model_name="connectionlog",
            index=models.Index(fields=["ip_address"], name="shop_connec_ip_addr_9ff739_idx"),
        ),
    ]
