# Generated by Django 4.2.25 on 2025-12-06 19:23

from django.db import migrations


def clear_hero_title(apps, schema_editor):
    SiteSettings = apps.get_model("shop", "SiteSettings")
    SiteSettings.objects.filter(hero_title="Welcome to Blueprint").update(hero_title="")


def restore_hero_title(apps, schema_editor):
    SiteSettings = apps.get_model("shop", "SiteSettings")
    SiteSettings.objects.filter(hero_title="").update(hero_title="Welcome to Blueprint")


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clear_hero_title, restore_hero_title),
    ]
