# Generated by Django 4.2.25 on 2025-11-24 11:45
# Migration to create CampaignMessage table for production databases

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_expensecategory_revenue_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Welcome Email', 'Day 3 Follow-up SMS'", max_length=200
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("snapchat", "Snapchat"),
                            ("youtube", "YouTube"),
                            ("promotion", "Promotion"),
                            ("product", "Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("custom_subject", models.CharField(blank=True, max_length=200)),
                ("custom_content", models.TextField(blank=True)),
                (
                    "send_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-send"),
                            ("draft", "Save as Draft"),
                            ("manual", "Manual Approval Required"),
                        ],
                        default="auto",
                        help_text="How this message should be sent",
                        max_length=20,
                    ),
                ),
                (
                    "media_urls",
                    models.TextField(
                        blank=True,
                        help_text="URLs for images, videos, or other media (one per line)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes, content ideas, or reminders"
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Send Immediately"),
                            ("delay", "Send After Delay"),
                            ("specific_date", "Send on Specific Date"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                (
                    "delay_days",
                    models.IntegerField(
                        default=0,
                        help_text="Days to wait before sending (if trigger_type is 'delay')",
                    ),
                ),
                (
                    "delay_hours",
                    models.IntegerField(default=0, help_text="Hours to wait before sending"),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Specific date/time to send (if trigger_type is 'specific_date')",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("draft", "Draft"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of this message in the campaign sequence"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="shop.campaign",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional discount to associate with this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_messages",
                        to="shop.discount",
                    ),
                ),
                (
                    "email_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.emailtemplate",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific products this message applies to (optional)",
                        related_name="campaign_messages",
                        to="shop.product",
                    ),
                ),
                (
                    "sms_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.smstemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["campaign", "order", "created_at"],
            },
        ),
    ]
