# Generated by Django 4.2.25 on 2025-11-24 11:55
# Migration to create Campaign and CampaignMessage tables for production databases
# Uses RunSQL to safely create tables only if they don't exist

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_expensecategory_revenue_expense'),
    ]

    operations = [
        # Create Campaign table if it doesn't exist
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS shop_campaign (
                id BIGSERIAL PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                status VARCHAR(20) NOT NULL,
                channel VARCHAR(20) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                start_date TIMESTAMP WITH TIME ZONE,
                end_date TIMESTAMP WITH TIME ZONE,
                total_sent INTEGER NOT NULL DEFAULT 0,
                total_opened INTEGER NOT NULL DEFAULT 0,
                total_clicked INTEGER NOT NULL DEFAULT 0,
                total_converted INTEGER NOT NULL DEFAULT 0,
                revenue_generated NUMERIC(10, 2) NOT NULL DEFAULT 0
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS shop_campaign CASCADE;"
        ),

        # Create EmailTemplate table if it doesn't exist (required for CampaignMessage FK)
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS shop_emailtemplate (
                id BIGSERIAL PRIMARY KEY,
                name VARCHAR(200) NOT NULL UNIQUE,
                subject VARCHAR(200) NOT NULL,
                body_html TEXT NOT NULL,
                body_text TEXT NOT NULL DEFAULT '',
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                last_used TIMESTAMP WITH TIME ZONE,
                notes TEXT NOT NULL DEFAULT '',
                folder_id BIGINT
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS shop_emailtemplate CASCADE;"
        ),

        # Create SMSTemplate table if it doesn't exist (required for CampaignMessage FK)
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS shop_smstemplate (
                id BIGSERIAL PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                body TEXT NOT NULL,
                character_count INTEGER NOT NULL DEFAULT 0,
                segment_count INTEGER NOT NULL DEFAULT 1,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS shop_smstemplate CASCADE;"
        ),

        # Create CampaignMessage table if it doesn't exist
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS shop_campaignmessage (
                id BIGSERIAL PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                message_type VARCHAR(20) NOT NULL,
                custom_subject VARCHAR(200) NOT NULL DEFAULT '',
                custom_content TEXT NOT NULL DEFAULT '',
                send_mode VARCHAR(20) NOT NULL DEFAULT 'auto',
                media_urls TEXT NOT NULL DEFAULT '',
                notes TEXT NOT NULL DEFAULT '',
                trigger_type VARCHAR(20) NOT NULL DEFAULT 'immediate',
                delay_days INTEGER NOT NULL DEFAULT 0,
                delay_hours INTEGER NOT NULL DEFAULT 0,
                scheduled_date TIMESTAMP WITH TIME ZONE,
                status VARCHAR(20) NOT NULL DEFAULT 'pending',
                total_recipients INTEGER NOT NULL DEFAULT 0,
                sent_count INTEGER NOT NULL DEFAULT 0,
                failed_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                sent_at TIMESTAMP WITH TIME ZONE,
                "order" INTEGER NOT NULL DEFAULT 0,
                campaign_id BIGINT NOT NULL REFERENCES shop_campaign(id) ON DELETE CASCADE,
                discount_id BIGINT REFERENCES shop_discount(id) ON DELETE SET NULL,
                email_template_id BIGINT REFERENCES shop_emailtemplate(id) ON DELETE SET NULL,
                sms_template_id BIGINT REFERENCES shop_smstemplate(id) ON DELETE SET NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS shop_campaignmessage CASCADE;"
        ),

        # Create many-to-many table for CampaignMessage products
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS shop_campaignmessage_products (
                id BIGSERIAL PRIMARY KEY,
                campaignmessage_id BIGINT NOT NULL REFERENCES shop_campaignmessage(id) ON DELETE CASCADE,
                product_id BIGINT NOT NULL REFERENCES shop_product(id) ON DELETE CASCADE,
                UNIQUE (campaignmessage_id, product_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS shop_campaignmessage_products CASCADE;"
        ),

        # Create indexes
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS shop_campaignmessage_campaign_id_idx
                ON shop_campaignmessage(campaign_id);
            CREATE INDEX IF NOT EXISTS shop_campaignmessage_discount_id_idx
                ON shop_campaignmessage(discount_id);
            CREATE INDEX IF NOT EXISTS shop_campaignmessage_email_template_id_idx
                ON shop_campaignmessage(email_template_id);
            CREATE INDEX IF NOT EXISTS shop_campaignmessage_sms_template_id_idx
                ON shop_campaignmessage(sms_template_id);
            """,
            reverse_sql="-- No reverse needed for indexes"
        ),
    ]
