# Generated by Django 4.2.25 on 2026-01-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_clear_hero_title_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_for_purchase",
            field=models.BooleanField(
                default=True,
                help_text="If False, product is visible but shows 'Not Available' instead of Add to Cart",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title",
            field=models.CharField(
                blank=True, default="", help_text="Main headline on homepage", max_length=200
            ),
        ),
    ]
