# Generated by Django 4.2.25 on 2025-11-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_expensecategory_revenue_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmessage',
            name='landing_url',
            field=models.URLField(
                blank=True,
                help_text='Landing page URL for this post/message (e.g., https://site.com/products)',
            ),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='utm_source',
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text='UTM Source (e.g., instagram, tiktok, email)',
            ),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='utm_medium',
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text='UTM Medium (e.g., social, post, story)',
            ),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='utm_campaign',
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text='UTM Campaign name (e.g., spring_launch_2025)',
            ),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='utm_content',
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text='UTM Content (optional, for A/B testing different creatives)',
            ),
        ),
    ]
