# Generated by Django 4.2.25 on 2025-11-21 04:41
# NOTE: This migration is now a no-op since 0002a handles all these changes
# Kept to maintain migration numbering consistency

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002a_create_campaign_and_campaignmessage'),
    ]

    operations = [
        # All operations moved to 0002a_create_campaign_and_campaignmessage
        # This migration is kept as a no-op to maintain migration chain
    ]
