# Generated by Django 4.2.25 on 2026-01-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_available_for_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Attribute name (e.g., Waist, Inseam)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this attribute')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this attribute is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Attribute',
                'verbose_name_plural': 'Custom Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='The attribute value (e.g., 28, 30, 32)', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this value')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(help_text='The attribute this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.customattribute')),
            ],
            options={
                'verbose_name': 'Custom Attribute Value',
                'verbose_name_plural': 'Custom Attribute Values',
                'ordering': ['attribute', 'display_order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
