# Generated by Django 4.2.25 on 2025-11-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_campaignmessage_landing_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmessage',
            name='clicks',
            field=models.IntegerField(default=0, help_text='Number of clicks on the tracking URL'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='conversions',
            field=models.IntegerField(default=0, help_text='Number of conversions (purchases) from this message'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated from this message', max_digits=10),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='test_tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags for testing (e.g., 'emoji,urgency,discount50')", max_length=255),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='variant_name',
            field=models.CharField(blank=True, help_text="Variant identifier (e.g., 'A', 'B', 'Emoji Version', 'Short Copy')", max_length=50),
        ),
        migrations.AddField(
            model_name='discount',
            name='test_tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags for testing (e.g., 'percentage,newcustomer,holiday')", max_length=255),
        ),
        migrations.AddField(
            model_name='discount',
            name='variant_name',
            field=models.CharField(blank=True, help_text="Variant identifier (e.g., 'A', 'B', '20%', '50%')", max_length=50),
        ),
    ]
