# Generated by Django 4.2.25 on 2025-11-07 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_address_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('marketing_emails', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="E.g., 'Home', 'Work', 'Mom's House'", max_length=50)),
                ('full_name', models.CharField(max_length=120)),
                ('line1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='US', help_text='2-letter country code', max_length=2)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved addresses',
                'ordering': ['-is_default_shipping', '-created_at'],
            },
        ),
    ]
