# Generated by Django 4.2.25 on 2025-11-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_campaignmessage_clicks_campaignmessage_conversions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="last_used",
            field=models.DateTimeField(
                blank=True, help_text="Last time this template was used", null=True
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes about this template"),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="tags",
            field=models.TextField(blank=True, help_text="Comma-separated tags for categorization"),
        ),
        migrations.AddField(
            model_name="smstemplate",
            name="last_used",
            field=models.DateTimeField(
                blank=True, help_text="Last time this template was used", null=True
            ),
        ),
        migrations.AddField(
            model_name="smstemplate",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes about this template"),
        ),
        migrations.AddField(
            model_name="smstemplate",
            name="tags",
            field=models.TextField(blank=True, help_text="Comma-separated tags for categorization"),
        ),
    ]
