# Generated by Django 4.2.25 on 2026-02-02 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('subject', models.CharField(blank=True, help_text='Subject line (for emails only)', max_length=200)),
                ('content', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially Sent'), ('failed', 'Failed')], default='sending', max_length=20)),
                ('recipient_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Message',
                'verbose_name_plural': 'Quick Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='quick_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='shop.quickmessage'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='quick_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='shop.quickmessage'),
        ),
        migrations.AddIndex(
            model_name='quickmessage',
            index=models.Index(fields=['-sent_at'], name='quickmsg_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='quickmessage',
            index=models.Index(fields=['message_type', '-sent_at'], name='quickmsg_type_idx'),
        ),
    ]
