# Generated by Django 4.2.25 on 2025-11-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_emailtemplate_last_used_emailtemplate_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='design_json',
            field=models.JSONField(blank=True, help_text='Visual email builder design data (JSON format from Unlayer)', null=True),
        ),
    ]
