# Generated by Django 4.2.25 on 2025-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_add_visual_design_to_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='folder',
            field=models.CharField(choices=[('general', 'General'), ('marketing', 'Marketing'), ('transactional', 'Transactional'), ('seasonal', 'Seasonal'), ('onboarding', 'Onboarding'), ('notifications', 'Notifications')], default='general', help_text='Organize templates into folders for better organization', max_length=50),
        ),
    ]
