# Generated by Django 4.2.25 on 2025-11-22 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_add_folder_to_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='folder',
            field=models.CharField(default='general', help_text='Organize templates into folders for better organization', max_length=50),
        ),
        migrations.CreateModel(
            name='TemplateFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Folder',
                'verbose_name_plural': 'Template Folders',
                'ordering': ['display_name'],
            },
        ),
    ]
