# Generated by Django 4.2.25 on 2025-11-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_emailcampaign_alter_emailsubscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero image for the homepage', null=True, upload_to='site/hero/')),
                ('hero_title', models.CharField(default='Welcome to Blueprint', help_text='Main headline on homepage', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Subheadline or description on homepage')),
                ('site_name', models.CharField(default='Blueprint Apparel', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable to show maintenance page to non-staff users')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
