# Generated by Django 4.2.25 on 2025-11-18 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('landing_page', models.CharField(max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=1000, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_views', models.IntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=1000, null=True)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['-viewed_at'], name='shop_pagevi_viewed__7233af_idx'), models.Index(fields=['path', '-viewed_at'], name='shop_pagevi_path_a54b91_idx'), models.Index(fields=['referrer_domain', '-viewed_at'], name='shop_pagevi_referre_a7bbb8_idx')],
            },
        ),
    ]
