# Generated by Django 4.2.25 on 2026-02-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_add_test_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quickmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Quick Message",
                "verbose_name_plural": "Quick Messages",
            },
        ),
        migrations.RemoveIndex(
            model_name="quickmessage",
            name="quickmsg_type_idx",
        ),
        migrations.AlterField(
            model_name="quickmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="quickmessage",
            index=models.Index(fields=["message_type", "-created_at"], name="quickmsg_type_idx"),
        ),
    ]
