# Generated by Django 4.2.25 on 2025-11-18 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_pageview_city_pageview_country_pageview_country_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('target_group', models.CharField(blank=True, help_text="e.g., 'All Subscribers', 'New Customers', 'VIP'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Welcome Email', 'Day 3 Follow-up SMS'", max_length=200)),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('custom_subject', models.CharField(blank=True, max_length=200)),
                ('custom_content', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('immediate', 'Send Immediately'), ('delay', 'Send After Delay'), ('specific_date', 'Send on Specific Date')], default='immediate', max_length=20)),
                ('delay_days', models.IntegerField(default=0, help_text="Days to wait before sending (if trigger_type is 'delay')")),
                ('delay_hours', models.IntegerField(default=0, help_text='Hours to wait before sending')),
                ('scheduled_date', models.DateTimeField(blank=True, help_text="Specific date/time to send (if trigger_type is 'specific_date')", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of this message in the campaign sequence')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.campaign')),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.emailtemplate')),
                ('sms_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.smstemplate')),
            ],
            options={
                'ordering': ['campaign', 'order', 'created_at'],
            },
        ),
    ]
