# Generated by Django 4.2.25 on 2026-02-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_bundle_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Base cost for this product (used for profit calculations)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost for this specific variant (leave blank to use product base cost)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
