# Generated by Django 4.2.25 on 2025-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_campaign_campaignmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active_from',
            field=models.DateTimeField(blank=True, help_text='Campaign becomes active from this date', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='Campaign remains active until this date', null=True),
        ),
    ]
