# Generated by Django 4.2.25 on 2025-11-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_campaign_active_from_campaign_active_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmessage',
            name='media_urls',
            field=models.TextField(blank=True, help_text='URLs for images, videos, or other media (one per line)'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes, content ideas, or reminders'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='send_mode',
            field=models.CharField(choices=[('auto', 'Auto-send'), ('draft', 'Save as Draft'), ('manual', 'Manual Approval Required')], default='auto', help_text='How this message should be sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='message_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
