# Generated by Django 4.2.25 on 2026-02-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_add_cost_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Friendly name for this shipment (e.g., 'Spring 2025 Restock')",
                max_length=200,
            ),
        ),
    ]
