# Generated by Django 4.2.25 on 2026-02-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_shipment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="show_includes",
            field=models.BooleanField(
                default=True,
                help_text="Show 'Includes' section with component products on bundle page",
            ),
        ),
    ]
