# Generated by Django 4.2.25 on 2026-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_bundle_show_includes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="use_component_pricing",
            field=models.BooleanField(
                default=False, help_text="Use sum of component prices instead of fixed price"
            ),
        ),
        migrations.AlterField(
            model_name="bundle",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed bundle price (optional if using component pricing)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
