# Generated by Django 4.2.25 on 2025-11-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_base_price_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_urls',
            field=models.TextField(blank=True, help_text='Product images (one URL per line, max 15 images)'),
        ),
    ]
