# Generated by Django 4.2.25 on 2025-11-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Optional discount to associate with this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_messages', to='shop.discount'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Specific products this message applies to (optional)', related_name='campaign_messages', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='campaignmessage',
            name='message_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('youtube', 'YouTube'), ('promotion', 'Promotion')], max_length=20),
        ),
    ]
