# Generated by Django 4.2.25 on 2025-11-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_product_image_urls_campaignmessage_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('bogo', 'Buy One Get One'), ('free_shipping', 'Free Shipping')], default='percentage', max_length=20),
        ),
    ]
