# Generated by Django 4.2.25 on 2026-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_bundle_available_for_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customattribute',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Product Attribute', 'verbose_name_plural': 'Product Attributes'},
        ),
        migrations.AlterModelOptions(
            name='customattributevalue',
            options={'ordering': ['attribute', 'display_order', 'value'], 'verbose_name': 'Product Attribute Value', 'verbose_name_plural': 'Product Attribute Values'},
        ),
        migrations.AddField(
            model_name='customattribute',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which to display this attribute (lower = first)'),
        ),
        migrations.AddField(
            model_name='customattribute',
            name='input_type',
            field=models.CharField(choices=[('select', 'Dropdown/Buttons'), ('color', 'Color Swatches'), ('text', 'Text Input')], default='select', help_text='How this attribute should be displayed in the UI', max_length=20),
        ),
        migrations.AddField(
            model_name='customattributevalue',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Additional data for this value (e.g., {'hex_code': '#FF0000'} for colors)"),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='All attribute values for this variant (Size, Color, etc.)', related_name='variants', to='shop.customattributevalue'),
        ),
        migrations.AlterField(
            model_name='customattribute',
            name='name',
            field=models.CharField(help_text='Attribute name (e.g., Size, Color, Waist)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customattributevalue',
            name='value',
            field=models.CharField(help_text='The attribute value (e.g., M, Red, 32)', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_attributes',
            field=models.JSONField(blank=True, default=dict, help_text="DEPRECATED: Use 'attributes' ManyToMany field instead"),
        ),
    ]
