# Generated by Django 4.2.25 on 2026-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_migrate_to_unified_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_slides",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Hero slideshow slides. Each slide has: image_url, alt_text, link_url (optional)",
            ),
        ),
    ]
