# Generated by Django 4.2.25 on 2025-11-19 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_material_productvariant_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('uses_size', models.BooleanField(default=False, help_text='Does this category use size variants?')),
                ('uses_color', models.BooleanField(default=False, help_text='Does this category use color variants?')),
                ('uses_material', models.BooleanField(default=False, help_text='Does this category use material variants?')),
                ('custom_attributes', models.JSONField(blank=True, default=list, help_text='Custom variant attributes specific to this category')),
                ('common_fields', models.JSONField(blank=True, default=list, help_text='Common custom fields that products in this category typically have')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_legacy',
            field=models.CharField(blank=True, db_column='category', db_index=True, help_text='DEPRECATED: Old category field', max_length=100),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic variant attributes based on category configuration'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for this specific variant', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_obj',
            field=models.ForeignKey(blank=True, help_text='Product category - determines available variant attributes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category'),
        ),
    ]
