# Generated by Django 4.2.25 on 2026-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_hero_slides"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickmessage",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule message to be sent at this time (leave empty to send immediately)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quickmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("partial", "Partially Sent"),
                    ("failed", "Failed"),
                ],
                default="sending",
                max_length=20,
            ),
        ),
    ]
