# Generated by Django 4.2.25 on 2025-11-19 03:49

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')

    default_categories = [
        {
            'name': 'T-Shirts',
            'slug': 't-shirts',
            'description': 'Classic t-shirts and graphic tees',
            'uses_size': True,
            'uses_color': True,
            'uses_material': True,
            'custom_attributes': [],
            'common_fields': [
                {'name': 'Fit', 'type': 'text'},
                {'name': 'Neck Style', 'type': 'text'},
                {'name': 'Care Instructions', 'type': 'text'},
            ]
        },
        {
            'name': 'Hoodies',
            'slug': 'hoodies',
            'description': 'Hoodies and sweatshirts',
            'uses_size': True,
            'uses_color': True,
            'uses_material': True,
            'custom_attributes': [],
            'common_fields': [
                {'name': 'Style', 'type': 'text'},
                {'name': 'Hood Type', 'type': 'text'},
                {'name': 'Pocket Type', 'type': 'text'},
            ]
        },
        {
            'name': 'Pants',
            'slug': 'pants',
            'description': 'Pants, jeans, and trousers',
            'uses_size': True,
            'uses_color': True,
            'uses_material': True,
            'custom_attributes': [
                {
                    'name': 'Waist Size',
                    'type': 'select',
                    'options': ['28', '30', '32', '34', '36', '38', '40', '42']
                },
                {
                    'name': 'Inseam',
                    'type': 'select',
                    'options': ['28', '30', '32', '34', '36']
                }
            ],
            'common_fields': [
                {'name': 'Fit', 'type': 'text'},
                {'name': 'Rise', 'type': 'text'},
                {'name': 'Closure Type', 'type': 'text'},
            ]
        },
        {
            'name': 'Outerwear',
            'slug': 'outerwear',
            'description': 'Jackets, coats, and outerwear',
            'uses_size': True,
            'uses_color': True,
            'uses_material': True,
            'custom_attributes': [],
            'common_fields': [
                {'name': 'Warmth Rating', 'type': 'text'},
                {'name': 'Water Resistance', 'type': 'text'},
                {'name': 'Lining Material', 'type': 'text'},
            ]
        },
        {
            'name': 'Accessories',
            'slug': 'accessories',
            'description': 'Hats, bags, belts, and other accessories',
            'uses_size': False,
            'uses_color': True,
            'uses_material': True,
            'custom_attributes': [
                {
                    'name': 'Type',
                    'type': 'select',
                    'options': ['Hat', 'Bag', 'Belt', 'Scarf', 'Wallet', 'Other']
                }
            ],
            'common_fields': [
                {'name': 'Dimensions', 'type': 'text'},
                {'name': 'Capacity', 'type': 'text'},
            ]
        },
        {
            'name': 'Footwear',
            'slug': 'footwear',
            'description': 'Shoes, sneakers, and boots',
            'uses_size': True,
            'uses_color': True,
            'uses_material': True,
            'custom_attributes': [
                {
                    'name': 'Width',
                    'type': 'select',
                    'options': ['Narrow', 'Medium', 'Wide', 'Extra Wide']
                }
            ],
            'common_fields': [
                {'name': 'Sole Material', 'type': 'text'},
                {'name': 'Heel Height', 'type': 'text'},
                {'name': 'Closure Type', 'type': 'text'},
            ]
        },
        {
            'name': 'Sweatshirts',
            'slug': 'sweatshirts',
            'description': 'Crewneck sweatshirts and pullovers',
            'uses_size': True,
            'uses_color': True,
            'uses_material': True,
            'custom_attributes': [],
            'common_fields': [
                {'name': 'Weight', 'type': 'text'},
                {'name': 'Neckline', 'type': 'text'},
            ]
        },
        {
            'name': 'Shorts',
            'slug': 'shorts',
            'description': 'Shorts and swim trunks',
            'uses_size': True,
            'uses_color': True,
            'uses_material': True,
            'custom_attributes': [
                {
                    'name': 'Inseam Length',
                    'type': 'select',
                    'options': ['5"', '7"', '9"', '11"']
                }
            ],
            'common_fields': [
                {'name': 'Style', 'type': 'text'},
                {'name': 'Closure Type', 'type': 'text'},
            ]
        },
    ]

    for cat_data in default_categories:
        Category.objects.get_or_create(
            slug=cat_data['slug'],
            defaults=cat_data
        )


def reverse_default_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    slugs = ['t-shirts', 'hoodies', 'pants', 'outerwear', 'accessories', 'footwear', 'sweatshirts', 'shorts']
    Category.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_category_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
