# Generated by Django 4.2.25 on 2026-02-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_add_quickmessage_scheduling"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Stripe Dashboard')", max_length=100
                    ),
                ),
                ("url", models.URLField(help_text="Full URL to the service")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="fa-link",
                        help_text="FontAwesome icon class (e.g., 'fa-stripe', 'fa-github', 'fa-server')",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("payments", "Payments"),
                            ("hosting", "Hosting"),
                            ("shipping", "Shipping"),
                            ("development", "Development"),
                            ("marketing", "Marketing"),
                            ("analytics", "Analytics"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Lower numbers appear first"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
    ]
