# Generated by Django 4.2.25 on 2025-11-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_add_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('supplier', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('expected_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('item_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expected_date'],
            },
        ),
    ]
