# Generated by Django 4.2.25 on 2026-02-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_quick_links'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quickmessage',
            index=models.Index(fields=['status', 'scheduled_for'], name='quickmsg_scheduled_idx'),
        ),
    ]
