# Generated by Django 4.2.25 on 2026-02-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_add_quickmessage_scheduler_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="Hide this category from the storefront (products remain but category won't show in filters/navigation)"),
        ),
    ]
