# Generated by Django 4.2.25 on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_bugreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bug_report_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for bug report notifications (falls back to contact email)",
                max_length=254,
            ),
        ),
    ]
