# Generated by Django 4.2.25 on 2026-02-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0031_sitesettings_slideshow_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("AWAITING_PAYMENT", "Awaiting payment"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("CANCELED", "Canceled"),
                    ("REFUNDED", "Refunded"),
                    ("SHIPPED", "Shipped"),
                    ("FULFILLED", "Fulfilled"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
