# Generated by Django 4.2.25 on 2026-02-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0034_quicklink_notes_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(
                blank=True, help_text="Customer name (for manual orders)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, help_text="Customer phone number", max_length=20),
        ),
    ]
