# Generated by Django 4.2.25 on 2026-02-25 16:46

from django.db import migrations, models


def populate_order_numbers(apps, schema_editor):
    """Populate existing orders with order numbers."""
    Order = apps.get_model('shop', 'Order')
    for order in Order.objects.all().order_by('id'):
        order.order_number = f"BP-{10000 + order.id}"
        order.save(update_fields=['order_number'])


def reverse_order_numbers(apps, schema_editor):
    """Clear order numbers."""
    Order = apps.get_model('shop', 'Order')
    Order.objects.all().update(order_number='')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_add_order_customer_fields'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', help_text='Professional order number (e.g., BP-10001)', max_length=20),
        ),
        # Step 2: Populate existing orders
        migrations.RunPython(populate_order_numbers, reverse_order_numbers),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Professional order number (e.g., BP-10001)', max_length=20, unique=True),
        ),
    ]
