# Generated by Django 4.2.25 on 2026-03-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_add_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_oz',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product weight in ounces for shipping calculations (leave blank to use site default)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_product_weight_oz',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Default product weight in ounces (used when product has no weight set)', max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_city',
            field=models.CharField(blank=True, help_text='Warehouse city', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_country',
            field=models.CharField(default='US', help_text='Warehouse country code (e.g., US)', max_length=2),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_name',
            field=models.CharField(default='Blueprint Apparel', help_text='Business name for shipping labels', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_phone',
            field=models.CharField(blank=True, help_text='Warehouse phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_state',
            field=models.CharField(blank=True, help_text='Warehouse state/province', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_street1',
            field=models.CharField(blank=True, help_text='Warehouse street address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_street2',
            field=models.CharField(blank=True, help_text='Warehouse street address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warehouse_zip',
            field=models.CharField(blank=True, help_text='Warehouse postal code', max_length=20),
        ),
    ]
