# Generated by Django 4.2.25 on 2026-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_rename_twilio_sid_to_provider_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, help_text='Discount/promo code used', max_length=50),
        ),
    ]
