# Generated by Django 4.2.25 on 2026-03-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_add_order_discount_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('send_time', models.TimeField(help_text='Time to send the report (in America/Chicago timezone)')),
                ('weekly_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Day of week for weekly reports (0=Monday)')),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default='email', max_length=20)),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('sms_recipients', models.TextField(blank=True, help_text='Comma-separated phone numbers in E.164 format')),
                ('selected_metrics', models.JSONField(default=list, help_text='List of metric IDs to include in the report')),
                ('include_comparison', models.BooleanField(default=True, help_text='Include period-over-period comparison')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('total_sends', models.IntegerField(default=0)),
                ('failed_sends', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('email_sent', models.IntegerField(default=0)),
                ('email_failed', models.IntegerField(default=0)),
                ('sms_sent', models.IntegerField(default=0)),
                ('sms_failed', models.IntegerField(default=0)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('comparison_period_start', models.DateTimeField(blank=True, null=True)),
                ('comparison_period_end', models.DateTimeField(blank=True, null=True)),
                ('report_data', models.JSONField(default=dict, help_text='Snapshot of all metrics at the time of sending')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shop.scheduledreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
