# Generated by Django 4.2.25 on 2026-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_scheduled_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='weight_oz',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in ounces for this variant (leave blank to use product base weight)', max_digits=6, null=True),
        ),
    ]
