# Generated by Django 4.2.25 on 2026-03-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_add_variant_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Default tax rate percentage for in-person sales (e.g., 8.25 for 8.25%)', max_digits=5),
        ),
    ]
