# Generated by Django 4.2.25 on 2026-03-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_add_default_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost paid for shipping label', max_digits=10, null=True),
        ),
    ]
