# Generated by Django 4.2.25 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_add_label_cost_to_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['display_order', 'code']},
        ),
        migrations.AddField(
            model_name='color',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which to display (lower = first)'),
        ),
        migrations.AddField(
            model_name='size',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which to display (lower = first)'),
        ),
    ]
