# Generated by Django 4.2.25 on 2026-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0044_add_display_order_to_size_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="warehouse_email",
            field=models.EmailField(
                blank=True, help_text="Warehouse contact email", max_length=254
            ),
        ),
    ]
