# Generated by Django 4.2.25 on 2026-03-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_sitesettings_warehouse_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='lookbook_pages',
            field=models.JSONField(blank=True, default=list, help_text='Lookbook pages. Each page has: image_url, title, description, products (optional)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lookbook_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Lookbook settings: is_published, transition_type, etc.'),
        ),
    ]
