# Generated by Django 4.2.25 on 2026-03-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_add_lookbook_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Spring 2026', 'Fall Collection'", max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title (auto-generated)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this lookbook')),
                ('cover_image', models.URLField(blank=True, help_text='Cover image URL for listings')),
                ('pages', models.JSONField(blank=True, default=list, help_text='Lookbook pages. Each page has: image_url, title, description, position_x, position_y, zoom')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Lookbook settings: transition_type, etc.')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this lookbook is visible to the public')),
                ('is_featured', models.BooleanField(default=False, help_text='The featured lookbook is shown at /shop/lookbook/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
