# Generated by Django 4.2.25 on 2026-03-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_add_lookbook_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='news_ticker',
            field=models.JSONField(blank=True, default=dict, help_text='News ticker settings: enabled, text, background_color, text_color, speed'),
        ),
    ]
