# Generated by Django 4.2.25 on 2026-04-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0048_add_news_ticker_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="About page settings: banner_image, main_text, quote, etc.",
            ),
        ),
    ]
