# Generated by Django 4.2.25 on 2026-04-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0049_add_about_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for folder icon",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Folder",
                "verbose_name_plural": "Message Folders",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="quickmessage",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional folder for organizing messages",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="shop.messagefolder",
            ),
        ),
    ]
