# Generated by Django 4.2.25 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0050_add_message_folders"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefolder",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quickmessage",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
