# Generated by Django 4.2.25 on 2026-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0054_default_order_confirmation_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="auto_trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Only"),
                    ("on_subscribe", "On New Subscription"),
                    ("on_confirmation", "On Confirmation Request"),
                    ("on_order", "On New Order"),
                    ("on_shipping", "On Order Shipped"),
                    ("scheduled", "Scheduled Campaign"),
                ],
                default="manual",
                help_text="When should this template be automatically sent?",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome Message"),
                    ("confirmation", "Confirmation Email"),
                    ("promotion", "Promotional Email"),
                    ("newsletter", "Newsletter"),
                    ("announcement", "Announcement"),
                    ("order_confirmation", "Order Confirmation"),
                    ("shipping_notification", "Shipping Notification"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=25,
            ),
        ),
    ]
