# Generated by Django 4.2.25 on 2026-04-04 16:37
# Made idempotent - fields may already exist from earlier migrations

from django.db import migrations, models


def add_fields_if_missing(apps, schema_editor):
    """Add early access fields only if they don't already exist."""
    from django.db import connection

    db_vendor = connection.vendor

    fields_to_add = [
        ("early_access_code", "VARCHAR(50) DEFAULT ''"),
        ("early_access_enabled", "BOOLEAN DEFAULT FALSE"),
        ("early_access_include_staff", "BOOLEAN DEFAULT FALSE"),
        ("early_access_launch_at", "DATETIME NULL" if db_vendor == 'sqlite' else "TIMESTAMP WITH TIME ZONE NULL"),
    ]

    with connection.cursor() as cursor:
        if db_vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(shop_sitesettings)")
            existing_columns = [row[1] for row in cursor.fetchall()]
        else:
            cursor.execute("""
                SELECT column_name FROM information_schema.columns
                WHERE table_name = 'shop_sitesettings'
            """)
            existing_columns = [row[0] for row in cursor.fetchall()]

        for field_name, field_def in fields_to_add:
            if field_name not in existing_columns:
                cursor.execute(f"ALTER TABLE shop_sitesettings ADD COLUMN {field_name} {field_def}")


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0055_increase_template_type_length"),
    ]

    operations = [
        migrations.RunPython(add_fields_if_missing, migrations.RunPython.noop),
    ]
