# Generated by Django 4.2.25 on 2026-04-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0060_order_exclude_from_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(default="#6366f1", help_text="Hex color code", max_length=7),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="FontAwesome icon name (e.g., fa-star)", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("AWAITING_PAYMENT", "Awaiting payment"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("CANCELED", "Canceled"),
                    ("SHIPPED", "Shipped"),
                    ("FULFILLED", "Fulfilled"),
                    ("RETURN_REQUESTED", "Return requested"),
                    ("REFUNDED", "Refunded"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="orders", to="shop.ordertag"),
        ),
    ]
