# Generated by Django 5.1.7 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_ordertag_alter_order_status_order_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_shipping_code',
            field=models.CharField(blank=True, help_text='Free shipping code if applied', max_length=50),
        ),
    ]
