# Generated by Django 4.2.25 on 2026-05-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0066_update_admin_order_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage Off"),
                    ("fixed", "Fixed Amount Off"),
                    ("bogo", "Buy One Get One"),
                    ("free_shipping", "Free Shipping Code"),
                    ("auto_free_shipping", "Free Shipping Threshold"),
                ],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("AWAITING_PAYMENT", "Awaiting payment"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("CANCELED", "Canceled"),
                    ("SHIPPED", "Shipped"),
                    ("HAND_DELIVERED", "Hand delivered"),
                    ("FULFILLED", "Fulfilled"),
                    ("RETURN_REQUESTED", "Return requested"),
                    ("REFUNDED", "Refunded"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "order_number",
                    models.CharField(
                        blank=True,
                        help_text="Order number if inquiry is about an order",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to customer)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="contact_created_idx"),
                    models.Index(fields=["status"], name="contact_status_idx"),
                    models.Index(fields=["email"], name="contact_email_idx"),
                ],
            },
        ),
    ]
