# Generated by Django 4.2.25 on 2026-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0067_add_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="label_error",
            field=models.TextField(blank=True, help_text="Error message if label purchase failed"),
        ),
        migrations.AddField(
            model_name="order",
            name="label_purchased_at",
            field=models.DateTimeField(
                blank=True, help_text="When the shipping label was purchased", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.CharField(
                blank=True, help_text="Carrier selected at checkout (e.g., USPS)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_service",
            field=models.CharField(
                blank=True,
                help_text="Service selected at checkout (e.g., GroundAdvantage)",
                max_length=100,
            ),
        ),
    ]
