# Generated by Django 4.2.25 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0068_add_shipping_selection_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., USD, EUR, GBP)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full currency name (e.g., US Dollar, Euro)",
                        max_length=100,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol (e.g., $, €, £, CA$)",
                        max_length=10,
                    ),
                ),
                (
                    "symbol_position",
                    models.CharField(
                        choices=[
                            ("before", "Before amount (e.g., $10)"),
                            ("after", "After amount (e.g., 10€)"),
                        ],
                        default="before",
                        help_text="Position of symbol relative to amount",
                        max_length=10,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="Exchange rate from USD (e.g., 0.92 for EUR means 1 USD = 0.92 EUR)",
                        max_digits=12,
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Number of decimal places to display",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this currency is available for selection",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in currency selector (lower = first)",
                    ),
                ),
                (
                    "rate_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the exchange rate was last updated",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["display_order", "code"],
            },
        ),
    ]
