# Generated by Django 4.2.25 on 2026-05-20

from django.db import migrations


def seed_currencies(apps, schema_editor):
    """Seed initial currencies with approximate exchange rates."""
    Currency = apps.get_model("shop", "Currency")

    currencies = [
        {
            "code": "USD",
            "name": "US Dollar",
            "symbol": "$",
            "symbol_position": "before",
            "exchange_rate": 1.000000,
            "decimal_places": 2,
            "is_active": True,
            "display_order": 0,
        },
        {
            "code": "EUR",
            "name": "Euro",
            "symbol": "€",
            "symbol_position": "before",
            "exchange_rate": 0.920000,
            "decimal_places": 2,
            "is_active": True,
            "display_order": 1,
        },
        {
            "code": "GBP",
            "name": "British Pound",
            "symbol": "£",
            "symbol_position": "before",
            "exchange_rate": 0.790000,
            "decimal_places": 2,
            "is_active": True,
            "display_order": 2,
        },
        {
            "code": "CAD",
            "name": "Canadian Dollar",
            "symbol": "CA$",
            "symbol_position": "before",
            "exchange_rate": 1.360000,
            "decimal_places": 2,
            "is_active": True,
            "display_order": 3,
        },
        {
            "code": "AUD",
            "name": "Australian Dollar",
            "symbol": "A$",
            "symbol_position": "before",
            "exchange_rate": 1.530000,
            "decimal_places": 2,
            "is_active": True,
            "display_order": 4,
        },
        {
            "code": "RUB",
            "name": "Russian Ruble",
            "symbol": "₽",
            "symbol_position": "after",
            "exchange_rate": 89.500000,
            "decimal_places": 0,
            "is_active": True,
            "display_order": 5,
        },
    ]

    for currency_data in currencies:
        Currency.objects.get_or_create(
            code=currency_data["code"],
            defaults=currency_data,
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded currencies."""
    Currency = apps.get_model("shop", "Currency")
    Currency.objects.filter(code__in=["USD", "EUR", "GBP", "CAD", "AUD", "RUB"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0069_add_currency_model"),
    ]

    operations = [
        migrations.RunPython(seed_currencies, reverse_seed),
    ]
