# Generated by Django 4.2.25 on 2026-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0070_seed_initial_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discount code (leave blank for auto-apply)",
                max_length=50,
            ),
        ),
    ]
