# Generated by Django 4.2.25 on 2026-07-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0071_remove_unique_discount_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="show_hero_logo",
            field=models.BooleanField(
                default=True, help_text="Show the Blueprint logo on the hero section"
            ),
        ),
    ]
