# Generated by Django 4.2.25 on 2026-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0072_add_show_hero_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order in which to display (lower = first)"
            ),
        ),
    ]
