# Generated by Django 4.2.25 on 2026-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0073_add_category_display_order"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="category_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["is_hidden", "display_order"], name="category_visible_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category_obj", "is_active"], name="product_category_active_idx"
            ),
        ),
    ]
