# Generated by Django 4.2.25 on 2026-07-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0074_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Site favicon (displayed in browser tab)",
                null=True,
                upload_to="site/favicon/",
            ),
        ),
    ]
