# Generated by Django 4.2.25 on 2026-07-29 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0078_add_project_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "counted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "system_quantity",
                    models.IntegerField(help_text="Stock quantity when count started"),
                ),
                (
                    "physical_quantity",
                    models.IntegerField(blank=True, help_text="Actual counted quantity", null=True),
                ),
                ("difference", models.IntegerField(default=0)),
                (
                    "applied",
                    models.BooleanField(
                        default=False, help_text="Whether this correction was applied to stock"
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.stockcount",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_items",
                        to="shop.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["variant__product__name"],
                "unique_together": {("stock_count", "variant")},
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("count_correction", "Count Correction"),
                            ("damaged", "Damaged"),
                            ("sample", "Sample / Giveaway"),
                            ("gift", "Gift"),
                            ("return_received", "Return Received"),
                            ("theft", "Theft / Loss"),
                            ("shipment_received", "Shipment Received"),
                            ("order_sold", "Order Sold"),
                            ("manual", "Manual Adjustment"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("previous_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                ("difference", models.IntegerField()),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to="shop.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["variant", "-created_at"], name="stockadj_variant_idx"),
                    models.Index(fields=["-created_at"], name="stockadj_date_idx"),
                ],
            },
        ),
    ]
