# Generated by Django 4.2.25 on 2026-08-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0079_add_inventory_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size_guide",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Size guide data. Format: {"columns": ["Chest", "Length"], "sizes": {"S": ["38", "28"], "M": ["40", "29"]}}',
            ),
        ),
    ]
