# Generated by Django 4.2.25 on 2026-08-03 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0080_add_size_guide_to_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Reviewer display name", max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("rating", models.PositiveIntegerField(help_text="1-5 stars")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("is_verified_purchase", models.BooleanField(default=False)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, help_text="Auto-approved, can be hidden by admin"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["product", "-created_at"], name="review_product_idx")
                ],
            },
        ),
    ]
