# Generated by Django 4.2.25 on 2026-08-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0081_add_product_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("all", "All Subscribers"),
                    ("no_account", "Subscribers Without Account"),
                    ("customers", "Customers (Ordered Before)"),
                    ("review_request", "Review Request (Bought But No Review)"),
                ],
                default="all",
                help_text="Who should receive this email when sent",
                max_length=30,
            ),
        ),
    ]
